const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType
} = require("docx");
const ExcelJS = require("exceljs");
const PptxGenJS = require("pptxgenjs");
const { safeArtifactFilename } = require("./schema");

const MIME = Object.freeze({
  document: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  spreadsheet: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  presentation: "application/vnd.openxmlformats-officedocument.presentationml.presentation"
});

function buildDocumentChildren(spec) {
  const children = [
    new Paragraph({
      text: spec.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 360 }
    })
  ];
  for (const section of spec.sections) {
    if (section.heading) {
      children.push(new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 220, after: 100 }
      }));
    }
    for (const paragraph of section.paragraphs) {
      children.push(new Paragraph({
        children: [new TextRun({ text: paragraph, size: 22 })],
        spacing: { after: 140 }
      }));
    }
    for (const bullet of section.bullets) {
      children.push(new Paragraph({
        text: bullet,
        bullet: { level: 0 },
        spacing: { after: 80 }
      }));
    }
  }
  return children;
}

async function generateDocx(spec) {
  const doc = new Document({
    creator: "UNBOUND AI",
    title: spec.title,
    description: "Generated by UNBOUND AI Artifact Studio",
    sections: [{
      properties: {
        page: {
          margin: { top: 720, right: 720, bottom: 720, left: 720 }
        }
      },
      children: buildDocumentChildren(spec)
    }]
  });
  const buffer = await Packer.toBuffer(doc);
  return {
    buffer,
    mimeType: MIME.document,
    filename: safeArtifactFilename(spec.title, "docx")
  };
}

function autosizeColumns(worksheet, maxWidth = 42) {
  worksheet.columns.forEach((column) => {
    let longest = 10;
    column.eachCell?.({ includeEmpty: false }, (cell) => {
      const value = String(cell.value ?? "");
      longest = Math.max(longest, Math.min(value.length + 2, maxWidth));
    });
    column.width = longest;
  });
}

async function generateXlsx(spec) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "UNBOUND AI";
  workbook.title = spec.title;
  workbook.created = new Date();
  for (const sheetSpec of spec.sheets) {
    const sheet = workbook.addWorksheet(sheetSpec.name, {
      views: [{ state: "frozen", ySplit: sheetSpec.columns.length ? 1 : 0 }]
    });
    if (sheetSpec.columns.length) {
      const header = sheet.addRow(sheetSpec.columns);
      header.font = { bold: true };
      header.alignment = { vertical: "middle", horizontal: "left" };
      sheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: Math.max(1, sheetSpec.columns.length) }
      };
    }
    for (const row of sheetSpec.rows) {
      sheet.addRow(row);
    }
    autosizeColumns(sheet);
  }
  const data = await workbook.xlsx.writeBuffer();
  return {
    buffer: Buffer.from(data),
    mimeType: MIME.spreadsheet,
    filename: safeArtifactFilename(spec.title, "xlsx")
  };
}

function addTitle(slide, text) {
  slide.addText(text, {
    x: 0.7, y: 0.45, w: 11.9, h: 0.6,
    fontFace: "Aptos Display",
    fontSize: 26,
    bold: true,
    color: "102A43",
    margin: 0
  });
}

async function generatePptx(spec) {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "UNBOUND AI";
  pptx.subject = "Generated by UNBOUND AI Artifact Studio";
  pptx.title = spec.title;
  pptx.company = "UNBOUND AI";
  pptx.lang = "en-US";

  const cover = pptx.addSlide();
  cover.background = { color: "07111C" };
  cover.addText(spec.title, {
    x: 0.8, y: 2.15, w: 11.7, h: 1.0,
    fontFace: "Aptos Display",
    fontSize: 32,
    bold: true,
    color: "FFFFFF",
    align: "center",
    margin: 0
  });
  if (spec.subtitle) {
    cover.addText(spec.subtitle, {
      x: 1.2, y: 3.35, w: 10.9, h: 0.7,
      fontFace: "Aptos",
      fontSize: 17,
      color: "9CD8FF",
      align: "center",
      margin: 0
    });
  }
  cover.addText("UNBOUND AI", {
    x: 4.8, y: 6.45, w: 3.7, h: 0.35,
    fontFace: "Aptos",
    fontSize: 10,
    bold: true,
    color: "FFB95C",
    align: "center",
    charSpacing: 2
  });

  for (const slideSpec of spec.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: "F7FAFC" };
    addTitle(slide, slideSpec.title);
    const bullets = slideSpec.bullets.slice(0, 12);
    if (bullets.length) {
      const runs = bullets.map((text) => ({
        text,
        options: { bullet: { indent: 20 }, hanging: 4, breakLine: true }
      }));
      slide.addText(runs, {
        x: 0.95, y: 1.35, w: 11.35, h: 5.25,
        fontFace: "Aptos",
        fontSize: bullets.length > 8 ? 16 : 19,
        color: "243B53",
        valign: "top",
        breakLine: false,
        margin: 0.05,
        paraSpaceAfterPt: 9,
        fit: "shrink"
      });
    } else {
      slide.addText(" ", { x: 0.95, y: 1.35, w: 11.35, h: 5.25 });
    }
    slide.addText("UNBOUND AI", {
      x: 10.6, y: 7.05, w: 1.8, h: 0.22,
      fontSize: 8, color: "829AB1", align: "right", margin: 0
    });
    if (slideSpec.notes && typeof slide.addNotes === "function") {
      slide.addNotes(slideSpec.notes);
    }
  }

  const output = await pptx.write({ outputType: "nodebuffer", compression: true });
  return {
    buffer: Buffer.isBuffer(output) ? output : Buffer.from(output),
    mimeType: MIME.presentation,
    filename: safeArtifactFilename(spec.title, "pptx")
  };
}

async function generateArtifact(spec) {
  if (spec.type === "document") return generateDocx(spec);
  if (spec.type === "spreadsheet") return generateXlsx(spec);
  if (spec.type === "presentation") return generatePptx(spec);
  const error = new Error("Artifact type is unsupported.");
  error.code = "ARTIFACT_TYPE_INVALID";
  error.statusCode = 400;
  throw error;
}

module.exports = {
  MIME,
  generateDocx,
  generateXlsx,
  generatePptx,
  generateArtifact
};
